import type { StrategyDefinition } from '@/lib/types'

export const STRATEGIES: StrategyDefinition[] = [
  {
    id: 'covered-call',
    name: 'Covered Call',
    description: 'Own stock, sell an OTM call. Generates income in sideways to mildly bullish markets.',
    signals: { ivEnvironment: 'high', trend: 'bullish' },
    weight: 10,
    minExperienceLevel: 'beginner',
  },
  {
    id: 'cash-secured-put',
    name: 'Cash-Secured Put',
    description: 'Sell an OTM put backed by cash. Good for acquiring stock at a discount while collecting premium.',
    signals: { ivEnvironment: 'high', trend: 'bullish' },
    weight: 9,
    minExperienceLevel: 'beginner',
  },
  {
    id: 'iron-condor',
    name: 'Iron Condor',
    description: 'Sell OTM call spread + OTM put spread. Profits when the stock stays in a range.',
    signals: { ivEnvironment: 'high', trend: 'neutral' },
    weight: 10,
    minExperienceLevel: 'intermediate',
  },
  {
    id: 'bull-call-spread',
    name: 'Bull Call Spread',
    description: 'Buy a lower strike call, sell a higher strike call. Defined-risk bullish bet.',
    signals: { ivEnvironment: 'low', trend: 'bullish' },
    weight: 9,
    minExperienceLevel: 'beginner',
  },
  {
    id: 'bear-put-spread',
    name: 'Bear Put Spread',
    description: 'Buy a higher strike put, sell a lower strike put. Defined-risk bearish bet.',
    signals: { ivEnvironment: 'low', trend: 'bearish' },
    weight: 9,
    minExperienceLevel: 'beginner',
  },
  {
    id: 'long-call',
    name: 'Long Call',
    description: 'Buy a call option. Simple bullish bet with limited, defined risk.',
    signals: { ivEnvironment: 'low', trend: 'bullish' },
    weight: 7,
    minExperienceLevel: 'beginner',
  },
  {
    id: 'long-put',
    name: 'Long Put',
    description: 'Buy a put option. Simple bearish bet or portfolio hedge with limited risk.',
    signals: { ivEnvironment: 'low', trend: 'bearish' },
    weight: 7,
    minExperienceLevel: 'beginner',
  },
  {
    id: 'butterfly',
    name: 'Butterfly Spread',
    description: 'Buy one ITM, sell two ATM, buy one OTM call/put. Profits if stock stays near current price.',
    signals: { ivEnvironment: 'neutral', trend: 'neutral' },
    weight: 8,
    minExperienceLevel: 'intermediate',
  },
  {
    id: 'protective-put',
    name: 'Protective Put',
    description: 'Own stock + buy a put as downside insurance. Acts like portfolio insurance.',
    signals: { sentiment: 'bearish' },
    weight: 8,
    minExperienceLevel: 'beginner',
  },
  {
    id: 'straddle',
    name: 'Long Straddle',
    description: 'Buy an ATM call and ATM put. Profits from a big move in either direction.',
    signals: { ivEnvironment: 'low', trend: 'neutral' },
    weight: 7,
    minExperienceLevel: 'intermediate',
  },
]
